server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-server.p12
    key-store-password: auth-server-pass

    org:
      hibernate:
        dialect:
          PostgreSQLDialect:

spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/oauth2_server

security:
  token:
    key-store-path: classpath:keys/jwt.jks
    key-store-type: JKS
    key-store-password: password
    key-store-alias: jwt
    delete-older-than-secs: 86400
