server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/auth-server.p12
    key-store-password: auth-server-pass

spring:
  jpa:
    hibernate:
      ddl-auto: none

security:
  token:
    key-store-path: classpath:keys/jwt.jks
    key-store-type: JKS
    key-store-password: password
    key-store-alias: jwt
    delete-older-than-secs: 86400
