spring:
  jpa:
    properties:
      hibernate:
        default_schema: prod
  datasource:
    url: # TODO
    username: # TODO
    password: # TODO

logging:
  level:
    io.craigmiller160.authserver: INFO
    io.craigmiller160.webutils: INFO
