apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-oauth2-server-config
data:
  spring.profiles.active: prod
  spring.config.location: classpath:/config/common/,classpath:/config/prod/
  spring.datasource.host: postgres-service
  spring.datasource.port: "5432"
  spring.datasource.username: postgres_root
