apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-oauth2-server
  template:
    metadata:
      labels:
        app: sso-oauth2-server
    spec:
      containers:
        - name: sso-oauth2-server
          image: localhost:32000/sso-oauth2-server:1.5.0-SNAPSHOT
          ports:
            - containerPort: 8443
          envFrom:
            - configMapRef:
                name: sso-oauth2-server-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: sso-oauth2-server-service
spec:
  type: ClusterIP
  selector:
    app: sso-oauth2-server
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
